FROM mysql:5.7

# Environment variables
ENV MYSQL_DATABASE=patient_medical_history
ENV MYSQL_ROOT_PASSWORD=happypinpass
ENV MYSQL_USER=happypin
ENV MYSQL_PASSWORD=happypinpass

# Expose a port for container host consumption
EXPOSE 3306

